/**
 * Danh sách các tỉnh thành phố Việt Nam
 */
export const VIETNAM_CITIES = [
  'Hà Nội',
  'TP.HCM',
  'Đà Nẵng',
  'Hải Phòng',
  'Cần Thơ',
  'Biên Hòa',
  'Nha Trang',
  'Huế',
  'Vũng Tàu',
  'Buôn Ma Thuột',
  'Quy Nhơn',
  'Thái Nguyên',
  'Thái Bình',
  'Nam Định',
  'Phan Thiết',
  'Bắc Giang',
  'Bắc Ninh',
  'Hạ Long',
  'Cao Bằng',
  'Lạng Sơn',
  'Hòa Bình',
  'Sơn La',
  'Lai Châu',
  'Điện Biên Phủ',
  'Yên Bái',
  'Lào Cai',
  'Phú Thọ',
  'Vĩnh Phúc',
  'Hưng Yên',
  'Hải Dương',
  'Ninh Bình',
  'Thanh Hóa',
  'Nghệ An',
  'Hà Tĩnh',
  'Quảng Bình',
  'Quảng Trị',
  'Quảng Ngãi',
  'Bình Định',
  'Phú Yên',
  'Khánh Hòa',
  'Ninh Thuận',
  'Bình Thuận',
  'Kon Tum',
  'Gia Lai',
  'Đắk Lắk',
  'Đắk Nông',
  'Lâm Đồng',
  'Bình Phước',
  'Tây Ninh',
  'Bình Dương',
  'Đồng Nai',
  'Bà Rịa - Vũng Tàu',
  'Long An',
  'Tiền Giang',
  'Bến Tre',
  'Trà Vinh',
  'Vĩnh Long',
  'Đồng Tháp',
  'An Giang',
  'Kiên Giang',
  'Hậu Giang',
  'Sóc Trăng',
  'Bạc Liêu',
  'Cà Mau',
];

/**
 * Các bán kính tìm kiếm (km)
 */
export const SEARCH_RADIUS = [
  { label: '0 km (Chính xác)', value: 0 },
  { label: '5 km', value: 5 },
  { label: '10 km', value: 10 },
  { label: '20 km', value: 20 },
  { label: '30 km', value: 30 },
  { label: '50 km', value: 50 },
  { label: '100 km', value: 100 },
  { label: 'Toàn quốc', value: 9999 },
];

/**
 * Các mức kinh nghiệm
 */
export const EXPERIENCE_LEVELS = [
  { label: 'Chưa có kinh nghiệm', value: 'no-experience' },
  { label: 'Dưới 1 năm', value: 'under-1-year' },
  { label: '1-2 năm', value: '1-2-years' },
  { label: '2-5 năm', value: '2-5-years' },
  { label: '5-10 năm', value: '5-10-years' },
  { label: 'Trên 10 năm', value: 'over-10-years' },
];
